apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mysql
  name: mysql-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: das
        - name: MYSQL_USER
          value: dsa # missing config map
        - name: MYSQL_PASSWORD
          value: dsa
        - name: MYSQL_DATABASE
          value: dsa
        ports:
        - name: mysql
          containerPort: 3306
          hostPort: 3306
          # missing volume
