apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    run: rest-load-balancer
spec:
  selector:
    app: rest-deployment
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32708
  selector:
    run: rest-load-balancer
  type: NodePort
status:
  loadBalancer: {}
