apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      run: web-load-balancer
  replicas: 3
  template:
    metadata:
      labels:
        run: web-load-balancer
    spec:
      containers:
        - name: node-web
          image: aggelol/node-web
          ports:
            - containerPort: 8080
              protocol: TCP