apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-load-balancer
spec:
  selector:
    app: web-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32709
  selector:
    run: web-load-balancer
  type: NodePort
status:
  loadBalancer: {}
