apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web-load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        run: web-load-balancer
    spec:
      containers:
      - name: web
        image: aggelol/node-web
        ports:
          - containerPort: 8080
            protocol: TCP