FROM python:3.7-alpine
MAINTAINER August

WORKDIR /code

ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0

RUN apk add --no-cache \
  gcc \
  musl-dev \
  linux-headers

COPY . .
RUN pip install -r requirements.txt

CMD ["flask", "run"]
